# Site
title:              "Developer Perception to Microsoft’s Acquisition of GitHub"
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "Answers from contributors of Linux distributions/kernel and BSD families"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naist-se.github.io/study-of-microsofts-github-acquisition/" # the base hostname & protocol for your site



defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/survey/:title/"
    layout: post
    author:

# Jekyll
permalink:          /survey/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             naist-se

# personal
location:           8916-5 Takayama-cho, Ikoma, Nara 630-0192, JAPAN
phone:              +81-(743)-72-5111
email:              natnaree.asavaseri.mt9@is.naist.jp

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/survey/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
